name: Deploy latest pushed image to EKS

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get EKS credentials
        run: |
          aws eks update-kubeconfig --name kube-cluster --region ${{ secrets.AWS_REGION }}

      - name: Get image tag from payload
        id: get_image_tag
        run: |
          IMAGE_TAG=$(jq --raw-output .client_payload.image_tag <<< "$PAYLOAD")
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        env:
          PAYLOAD: ${{ toJSON(github.event) }}

      - name: Deploy to EKS
        run: |
          sed -i "s|<IMAGE_PLACEHOLDER>|${{ env.IMAGE_TAG }}|g" deployment.yml
          kubectl apply -f deployment.yml
